Code style
mtmse/dotify.formatter.impl pull request #13
Opened 2020-02-28 12:47 UTC by kalaspuffar

Hi @bertfrees and @PaulRambags

This is the first attempt to add a code style to the Dotify repositories.

In this iteration, I've added a checkstyle.xml with some basic rules for code style. Most of the code already followed these rules, but going through and fixing all the instances of tabs was easier using a ruleset.

With this pull request, I DON*T look for a discussion about code standards. My main goal was to solve the issue we had. If there is any rule that you are vehemently against, then we can remove that rule but if there are many things that we have different opinions on I see that the best solution is to close this pull request and create a new one with a checkstyle.xml file with only the spaces rule.

Best regards
Daniel

2020-03-02 08:12 UTC, PaulRambags requested changes
Hi @kalaspuffar, you made a decision to use CheckStyle, which is yet another checking mechanism - and I don't know how well it integrates with my current editor and how well it is still maintained. You could also have used PMD (which is already present), or Sonarqube (which is widely used and maintained well).

2020-03-02 10:04 UTC, bertfrees approved these changes

2020-03-02 10:14 UTC, kalaspuffar commented
Hi @PaulRambags 

The last release of Checkstyle was Feb 2020. Sonarqube I've used in a previous life, and it was a time sink without end. PMD did not mainly check for style and did not have a check for spacing, and building a custom one was more work than it was worth.

I don't think the tooling is an essential part as everything runs through Gradle. Because we want to change over to spaces, we need a way to verify that this has been done.

Best regards
Daniel

2020-03-02 13:51 UTC, PaulRambags approved these changes

2020-03-03 07:38 UTC, kalaspuffar commented
I've now run the regression tests without any regressions.

2020-03-03 07:39 UTC, merged