Don't cache translation of text segment if block has dynamic content
mtmse/dotify.formatter.impl pull request #39
Opened 2020-12-08 15:25 UTC by bertfrees

The braille translation of a text segment may depend on preceding and following segments whos value can change, notably "page-number" and "evaluate", so it may not be cached if such segments are present.

Fixes issue https://github.com/mtmse/dotify.formatter.impl/issues/38.

2020-12-08 15:30 UTC, bertfrees commented
(There was a checkstyle issue that I fixed.)

2020-12-08 17:53 UTC, PaulRambags requested changes

2020-12-08 17:53 UTC, PaulRambags commented on src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
> +    private final boolean dynamicContent;
dynamicContent -> hasDynamicContent

2020-12-08 17:53 UTC, PaulRambags commented on src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
> +            // following segments whos values can change, because this may influence the translation
whos -> whose

2020-12-08 19:57 UTC, bertfrees commented on src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
> +    private final boolean dynamicContent;
Done.

2020-12-08 19:57 UTC, bertfrees commented on src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
> +            // following segments whos values can change, because this may influence the translation
Done

2020-12-10 08:16 UTC, PaulRambags approved these changes

2020-12-10 12:51 UTC, kalaspuffar approved these changes

2020-12-10 12:52 UTC, kalaspuffar commented
PR approved. Will run regression tests.

2020-12-11 09:22 UTC, merged